apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
    - image: kilowulf/client
      context: client
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: kilowulf/comments
      context: comments
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: kilowulf/event-bus
      context: event-bus
      sync:
        manual:
          - src: "*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: kilowulf/moderation
      context: moderation
      sync:
        manual:
          - src: "*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: kilowulf/query
      context: query
      sync:
        manual:
          - src: "*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: kilowulf/posts
      context: posts
      sync:
        manual:
          - src: "*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
